//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDemoServicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPosition
    {
        public int id { get; set; }
        public Nullable<int> idAgente { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lon { get; set; }
        public DateTime Fecha { get; set; }
    
        public virtual Agente Agente { get; set; }
    }
}
